FROM node:5.6.0
MAINTAINER Chef Software, Inc. <docker@chef.io>

WORKDIR /usr/src/app

ENV DISPLAY :99
ENV CHROME_BIN /usr/bin/google-chrome

RUN mkdir -p /usr/src/app

RUN \
  apt-get update && \
  apt-get install -y chromium xvfb default-jdk rsync && \
  npm install -g jshint typings

COPY xvfb-chromium /usr/bin/xvfb-chromium
RUN ln -s /usr/bin/xvfb-chromium /usr/bin/google-chrome && \
  ln -s /usr/bin/xvfb-chromium /usr/bin/chromium-browser
