FROM centos:7
MAINTAINER Chef Software, Inc. <docker@chef.io>

EXPOSE 22

ENV SSH_USER devchef
ENV SSH_PASSWORD password

RUN yum update -y && \
    yum install openssh-server openssh-clients openssl sudo -y && \
    yum clean all && \
    mkdir -p /var/run/sshd && \
    mkdir -p /home

COPY init.sh /init.sh
RUN chmod +x /init.sh

CMD ["bash", "-c", "/init.sh"]
