FROM ubuntu:16.04
MAINTAINER Chef Software, Inc. <docker@chef.io>

EXPOSE 22

ENV SSH_USER devchef
ENV SSH_PASSWORD password

RUN apt-get update -y && \
    apt-get install openssh-server openssl sudo -y && \
    mkdir -p /var/run/sshd && \
    mkdir -p /home && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY init.sh /init.sh
RUN chmod +x /init.sh

CMD ["bash", "-c", "/init.sh"]
