FROM logstash:2.3.1
MAINTAINER Chef Software, Inc. <docker@chef.io>

RUN logstash-plugin install --development && \
  logstash-plugin install --no-verify uuidtools && \
  logstash-plugin install logstash-output-websocket && \
  logstash-plugin install logstash-filter-checksum && \
  logstash-plugin install logstash-filter-clone

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["logstash", "agent"]
